services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - app
    volumes:
      - ./prometheus.yml:/etc/prometheus/prom

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - app
    
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    networks:
      - app
    volumes:
      - '/:/host:ro,rslave'

networks:
  app:
    driver: bridge
    

